### ISSUE TITLE
Why do we need score normalization?

### ISSUE THREAD

**Issue by manifoldhiker** [WangWenhao0716/ISC-Track2-Submission#2]
Hello! Congratulations with the best results and thank you for such a good and well-documented solution!

I have a question regarding score normalization. In the paper, you wrote:
> scores of different queries are not comparable.

**Why are matching confidences not comparable between queries and why do we need score normalization?**

My best guess is that intra-cluster variability is different for different objects in our hyperspace.
For example, two classes: images of the sky and images of a human face. The first cluster is "more packed" and has less variability. For a query with a face, (cosine) distance of 0.8 might indicate that we have an exact match, while for the other class with less variability the same distance is too low for an exact match.

**Comment by WangWenhao0716** [comment]
Thanks for your interest. I agree with your guess. It’s reasonable!



发自我的iPhone


------------------ Original ------------------
From: mikhail kilianovski ***@***.***&gt;
Date: Sat,Dec 4,2021 10:09 PM
To: WangWenhao0716/ISC-Track2-Submission ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [WangWenhao0716/ISC-Track2-Submission] Why do we need score normalization? (Issue #2)





 
Hello! Congratulations with the best results and thank you for such a good and well-documented solution!
 
I have a question regarding score normalization. In the paper, you wrote:
  
scores of different queries are not comparable.
  
Why are matching confidences not comparable between queries and why do we need score normalization?
 
My best guess is that intra-cluster variability is different for different objects in our hyperspace.
 For example, two classes: images of the sky and images of a human face. The first cluster is "more packed" and has less variability. For a query with a face, (cosine) distance of 0.8 might indicate that we have an exact match, while for the other class with less variability the same distance is too low for an exact match.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
